// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg9vX6KuJmF79ncI1qcmGMBINwUPRXx34',
    appId: '1:832046690508:android:b7771d6b9f84cc0b69d269',
    messagingSenderId: '832046690508',
    projectId: 'drugapp-8242d',
    storageBucket: 'drugapp-8242d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsraLDEHD7unPuui0HE5fr3aGKwwMda-Q',
    appId: '1:832046690508:ios:67553adbbf397cf269d269',
    messagingSenderId: '832046690508',
    projectId: 'drugapp-8242d',
    storageBucket: 'drugapp-8242d.firebasestorage.app',
    iosBundleId: 'com.example.drugapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAuoVt4orKcBKY0aej5XleWwmVA03SHZo',
    appId: '1:832046690508:web:120032744c41fae969d269',
    messagingSenderId: '832046690508',
    projectId: 'drugapp-8242d',
    authDomain: 'drugapp-8242d.firebaseapp.com',
    storageBucket: 'drugapp-8242d.firebasestorage.app',
  );
}
